### ISSUE TITLE
transfer to real robot

### ISSUE THREAD

**Issue by zhouak47** [sled-group/navchat#2]
Thanks for your reply. I have successfully run the code using HM3D dataset.Now i want to use orion to actual robots ,and i am confused about this.Can you offer me the code you use in real robots and give some advise?Thanks a lot.

**Comment by YinpeiDai** [comment]
Hi, we're still oragnizing that real robot code, I can give you some details on that.

For real robot, we make serveral simplication as follows:
1. Instead of building VLMap, we use a topology graph to store the objects. For each scene, we use 7~12 predefined viewpoints, so when the robot called frontier-based exploration, we just do DFS in the topograph, and use groudingSAM to detect the objects during the movement. Once the object is found, the object will be updated in the topograph. Some landmark objects are also stored in the topograph. 
2. When a previous found object is asked again, we retrieve from the memory, find out the corresponding viewpoint, then directly call goto_viewpoint() to navigate the robot there. We build a room map with GMapping before the experiment, so the robot can move to a specific pose by using move_base without collision.

Hope this can help you!

**Comment by zhouak47** [comment]
Thanks for your kind reply
